### ISSUE TITLE
Missing downsized

### ISSUE THREAD

**Issue by emixam360** [Giphy/giphy-js-sdk-core#21]
Hello,

The js api is great, but origal size gif are heavy, is there a reson why "downsized", "downsized_still" and "downsized_large" sizes are not included in the returned objects ?

Thanks for the feedback

**Comment by Nolski** [comment]
Hey @emixam360, it looks like this may be a bug within our sdk. As a rule, `downsized` gifs must be under 2MB, `downsized_still` will just be a single framed version of `downsized`. If you're looking for something even smaller, `downsized_small` must be under 200KB.

**Comment by rodrigobdz** [comment]
@Nolski I noticed that `preview.gif_url` is also missing. The `preview` object I'm getting from the [API](https://developers.giphy.com/docs/) looks like this:
```json
{
      "frames": null,
      "gif_size": null,
      "gif_url": null,
      "height": "186",
      "media_id": "28bjfNBBerWUOW3A1H",
      "mp4_size": "37286",
      "mp4_url": "https://media2.giphy.com/media/28bjfNBBerWUOW3A1H/giphy-preview.mp4",
      "rendition_type": "preview",
      "webp_size": null,
      "webp_url": null,
      "width": "330",
}
```

**Comment by rodrigobdz** [comment]
@emixam360 Did you find a workaround for this?

**Comment by emixam360** [comment]
@rodrigobdz Nope, I stopped using the nodejs sdk

**Comment by Nolski** [comment]
@emixam360 @rodrigobdz I believe @cosmocochrane1 might be best suited to help you here as I think he is maintaining the JS SDK. 

A good alternative might be using the API directly which is documented [here](https://developers.giphy.com/docs/)

**Comment by rodrigobdz** [comment]
@cosmocochrane1 any clue why this is happening?

**Comment by rodrigobdz** [comment]
Well, it seems like the [API](https://developers.giphy.com/docs/) was updated and `preview.gif_url` is not available anymore. The new response object returns now `preview_gif.url` instead.

What's the status of the project?

**Comment by rodrigobdz** [comment]
@cosmocochrane1 I think we can close this issue. `downsized`, `downsized_still` and `downsized_large` are being returned. 
I will open a new issue regarding the `preview` object.
