### ISSUE TITLE
'isomorphic-fetch' breaks react-native projects

### ISSUE THREAD

**Issue by alexfoxy** [Giphy/giphy-js-sdk-core#22]
I can't use this api within a react native project as it conflicts with react natives own fetch.

To fix I have uncommented require('isomorphic-fetch'); from line 14 in RequestHandler.js

Is there a more solid fix?

**Comment by cosmocochrane1** [comment]
@alexfoxy i'll check it out!

**Comment by giannif** [comment]
@alexfoxy @cosmocochrane1 
We do need some sort of polyfill if we're going to support older browsers that don't have fetch. Perhaps there's a way to not pollute the global scope. 

There's this: https://www.npmjs.com/package/unfetch which is much smaller than the `isomorphic-fetch` lib I added way back when to support server side rendering, and it supports not polluting the global scope: https://www.npmjs.com/package/unfetch#usage

**Comment by rodrigobdz** [comment]
@alexfoxy @giannif could you check if the approach in #26 works for you?

**Comment by rodrigobdz** [comment]
I think this was fixed in #26. Close?

**Comment by cosmocochrane1** [comment]
@rodrigobdz I'm gonna confirm - have you tried to run it with a reactnative proj yet?

**Comment by rodrigobdz** [comment]
I am using the fix in a React Native project I am working on. I will create a new one to test in isolation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodrigobdz** [comment]
@cosmocochrane1  It's working for me. Feel free to try it out. I made a [MCVE](https://stackoverflow.com/help/mcve) which you can find [here](https://github.com/rodrigobdz/giphy-js-rn-fetch-bug).

There are two branches:
- [master](https://github.com/rodrigobdz/giphy-js-rn-fetch-bug) is running against [giphy-js-sdk-core ](https://github.com/Giphy/giphy-js-sdk-core/issues/22)**v1.0.3**.
- [giphy-js-sdk-core-v1.0.5](https://github.com/rodrigobdz/giphy-js-rn-fetch-bug/tree/giphy-js-sdk-core-v1.0.5) is running against [giphy-js-sdk-core](https://github.com/Giphy/giphy-js-sdk-core/issues/22) **v1.0.5**.

**Comment by cosmocochrane1** [comment]
@rodrigobdz radddd thanks taking a look now
