### ISSUE TITLE
Maintainer permissions

### ISSUE THREAD

**Issue by rodrigobdz** [Giphy/giphy-js-sdk-core#27]
I am using the SDK in a project and have encountered some bugs that could easily be fixed. There are some PRs that haven't been merged that should fix these bugs, as well as outdated issues.

I was [told](https://github.com/Giphy/giphy-js-sdk-core/issues/21#issuecomment-402455189) by @Nolski that @cosmocochrane1 is the one responsible for the repo. I would like to receive maintainer permissions to help with PRs and Issues.

**Comment by cosmocochrane1** [comment]
hey @rodrigobdz as much as I'd love to add you as a maintainer I cant, we have a company policy that only employees can maintain our projects. But I'm stoked on your help and will do my best to address all your issues as they come in! 👍

**Comment by rodrigobdz** [comment]
I understand. Thanks for your cooperation. We can close this then.

**Comment by cosmocochrane1** [comment]
@rodrigobdz getting you maintainer permissions today - I'm gonna set up a 2 person minimum approval for any PR. As we move along we can change that if we feel like we're moving too slow on PR's etc.

**Comment by cosmocochrane1** [comment]
@rodrigobdz whats your email

**Comment by rodrigobdz** [comment]
@cosmocochrane1 rodrigobermudezschettino@gmail.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodrigobdz** [comment]
We can close this again. 😄
