### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by rodrigobdz** [Giphy/giphy-js-sdk-core#28]
Where can I find a **changelog** for the npm package [giphy-js-sdk-core](https://yarnpkg.com/en/package/giphy-js-sdk-core)? Without it it's hard to notice what changes between versions.

What about [keep a changelog](https://keepachangelog.com/en/1.0.0/)?

**Comment by cosmocochrane1** [comment]
@rodrigobdz dope idea! I'll get onto it

**Comment by rodrigobdz** [comment]
Great. In order to save yourself some time it would be nice to integrate it into the contribution workflow as I suggested in [react-navigation](https://github.com/react-navigation/react-navigation/pull/4544#issuecomment-399355299).

**tl;dr**: 
> contributors provide a description of the changes made to the codebase together with the PR

**Comment by cosmocochrane1** [comment]
@rodrigobdz looking into getting you those maintainer permissions

**Comment by rodrigobdz** [comment]
I'll reference the [maintainer issue](https://github.com/Giphy/giphy-js-sdk-core/issues/27) for the sake of completeness.

**Comment by rodrigobdz** [comment]
@cosmocochrane1 Are there any updates on the matter? :)

**Comment by cosmocochrane1** [comment]
@rodrigobdz still waiting for the formal approval - looking like we're gonna make you a maintainer very soon though!
