### ISSUE TITLE
Missing code of conduct

### ISSUE THREAD

**Issue by rodrigobdz** [Giphy/giphy-js-sdk-core#31]
Quoting from [Github](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/):

> A code of conduct defines standards for how to engage in a community.

See [Facebook's](https://github.com/facebook/react-native/blob/e9e20e6c8335f27af8469cd23cb7ba079b0422f9/CODE_OF_CONDUCT.md) and [Microsoft's](https://opensource.microsoft.com/codeofconduct/) code of conduct.

**Comment by Nolski** [comment]
I wrote a code of conduct back in the day and I think I left it on the internal confluence. Might be a good use case for it here?

**Comment by cosmocochrane1** [comment]
@Nolski youre a legend. Happy birthday thank you

**Comment by rodrigobdz** [comment]
@Nolski It could be. Where can I find it?

**Comment by rodrigobdz** [comment]
Github recommends the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). What do you guys think about it?

**Comment by cosmocochrane1** [comment]
love that @rodrigobdz

**Comment by cosmocochrane1** [comment]
@Nolski I can't find it I say we just go with what @rodrigobdz just posted

**Comment by rodrigobdz** [comment]
Nice. I'll make a PR including the code of conduct.
