### ISSUE TITLE
Missing pull request template

### ISSUE THREAD

**Issue by rodrigobdz** [Giphy/giphy-js-sdk-core#35]
Recommended by Github to comply with [recommended community standards](https://opensource.guide/).

You can find how [Giphy Core SDK for JS](https://github.com/Giphy/giphy-js-sdk-core) compares to community standards [here](https://github.com/Giphy/giphy-js-sdk-core/community).

**Comment by cosmocochrane1** [comment]
@rodrigobdz lets close this out ye?

**Comment by rodrigobdz** [comment]
I am working on a PR for this.
