### ISSUE TITLE
Improve README structure

### ISSUE THREAD

**Issue by rodrigobdz** [Giphy/giphy-js-sdk-core#39]
**Is your feature request related to a problem? Please describe.**
The current README has a mixed structure and seems desorganized.

**Describe the solution you'd like**
Follow Github's [recommended format](https://guides.github.com/features/wikis/#Formatting-a-readme).

**Describe alternatives you've considered**
Follow a well-structured format.

**Comment by rodrigobdz** [comment]
@cosmocochrane1 I would suggest moving the supported endpoints documentation into a new file to keep the README as simple as possible. What do you think?

**Comment by dustfire** [comment]
hey @rodrigobdz we are keeping the README structure the same across all the SDKs, thanks for the suggestion.
