### ISSUE TITLE
Image object does not match API schema definition

### ISSUE THREAD

**Issue by josephrace** [Giphy/giphy-js-sdk-core#46]
Response from Image object does not match schema definition found in documentation (https://developers.giphy.com/docs/#images-object) e.g. `gif_url` vs `url`

This appears to have been fixed in this commit - https://github.com/Giphy/giphy-js-sdk-core/commit/5615a763d2a39a4d1d6b4908445d3b1221c9d3ab - however this change is not available in version 1.0.5.

Can you tell me when you plan to make a new release?

**Comment by rodrigobdz** [comment]
The [last commit](https://github.com/Giphy/giphy-js-sdk-core/commits/v1.0.5) that was merged into v1.0.5 was made on July 10th and the [PR](https://github.com/Giphy/giphy-js-sdk-core/pull/29) was made on July 17th. ping @cosmocochrane1

**Comment by cosmocochrane1** [comment]
I'll get a new version out tomorrow! Thanks @rodrigobdz

**Comment by rodrigobdz** [comment]
@josephrace v1.0.06 is out. Please open a new issue if you find another bug. Thanks!
