### ISSUE TITLE
giphy-js-sdk-core no longer implements CORS?

### ISSUE THREAD

**Issue by kristofferabell** [Giphy/giphy-js-sdk-core#50]
The SDK has been working great for me until version 1.0.6. Now all calls through the SDK get 

No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by rodrigobdz** [comment]
@kristofferabell What was the solution?

**Comment by kristofferabell** [comment]
@rodrigobdz I don't know if it was a problem with the API but it just worked when I woke up this morning. There was some adjustments to be made to fit the new structure of the response, but the No 'Access-Control-Allow-Origin' header solved itself. Which doesn't really make much sense to me..
