### ISSUE TITLE
'termSuggestion' endpoint does not work.

### ISSUE THREAD

**Issue by RobertCrowdis** [Giphy/giphy-js-sdk-core#51]
**Describe the bug**
termSuggestion returns a failure with an issue regarding CORS header, when other endpoints seem to be working fine.

**To Reproduce**
1. Try a request using .termSuggestions(). I have a demo listed below.

**Expected behavior**
I am expecting a response from the endpoint for 'termSuggestion' but instead I get a CORS error. I am not sure why this is the case if the search endpoint is allowing me to work. Pasting the request url into my browser bar returns `{"message":"You cannot consume this service"}`

**Reproducible Demo**

I have made an easy to follow, simple project. You can recreate the results too that cause this issue!
https://github.com/RobertCrowdis/giphy-sdk-example

**Desktop (please complete the following information):**
Running on latest version of Chrome as of 2/20/2019, Macbook Air with macOS High Sierra 10.13.4

**Comment by rodrigobdz** [comment]
Hi @RobertCrowdis! Thanks for the detailed issue report. I'm taking a look at your example.

**Comment by rodrigobdz** [comment]
The endpoint is not [documented](https://developers.giphy.com/docs/) anymore. @cosmocochrane1 Any alternative?

**Comment by RobertCrowdis** [comment]
Any updates on this issue?

**Comment by cosmocochrane1** [comment]
@RobertCrowdis we're waiting to hear back from our API team to decide what do moving forward with this endpoint. Thanks for writing in !

**Comment by nasarmientoo** [comment]
Hey! I'm having the same issue with Autocomplete API.`{message: 'You cannot consume this service'}` Any updates?

**Comment by nasarmientoo** [comment]
Hey! I'm having the same issue with Giphy Autocomplete API: {message: 'You cannot consume this service'}. How do you solved it?

**Comment by giannif** [comment]
Closing: This projected is deprecated, please reference the [fetch-api](https://github.com/Giphy/giphy-js/tree/master/packages/fetch-api) for a replacement
