### ISSUE TITLE
Whenever I run the command `npm install giphy-js-sdk-core` I get an error

### ISSUE THREAD

**Issue by LordIdren** [Giphy/giphy-js-sdk-core#53]
Whenever I run the command `npm install giphy-sdk-core` I get an error that says I can not install from "node_modules\giphy-js-sdk-core" as it does not contain a package.json file". I am pretty new to programming and I am confused as to what this means. 

[2019-09-15T04_01_51_822Zdebug.txt](https://github.com/Giphy/giphy-js-sdk-core/files/3613380/2019-09-15T04_01_51_822Zdebug.txt)

**Comment by rodrigobdz** [comment]
Were you able to find a solution to your problem?
